DROP SCHEMA IF EXISTS ext  CASCADE;
DROP SCHEMA IF EXISTS stg  CASCADE;
DROP SCHEMA IF EXISTS dds  CASCADE;
DROP SCHEMA IF EXISTS dm   CASCADE;
DROP SCHEMA IF EXISTS rep  CASCADE;
DROP SCHEMA IF EXISTS meta CASCADE;

CREATE SCHEMA ext;
CREATE SCHEMA stg;
CREATE SCHEMA dds;
CREATE SCHEMA dm;
CREATE SCHEMA rep;
CREATE SCHEMA meta;
