
GRANT USAGE ON SCHEMA ext, stg, dds, dm, meta TO rw_dwh;
GRANT CREATE ON SCHEMA ext TO rw_dwh;

GRANT ALL ON PROTOCOL pxf TO rw_dwh;
GRANT ALL ON PROTOCOL pxf TO airfGRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA meta TO rw_dwh;

GRANT ALL ON ALL SEQUENCES IN SCHEMA meta TO rw_dwh;
GRANT ALL ON ALL SEQUENCES IN SCHEMA meta TO airflow;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dm TO rw_dwh;


GRANT USAGE ON SCHEMA dm, rep TO ro_marts;
GRANT SELECT ON ALL TABLES IN SCHEMA dm TO ro_marts;

GRANT SELECT ON ALL TABLES IN SCHEMA rep TO ro_marts;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA rep TO ro_marts;


ALTER DEFAULT PRIVILEGES IN SCHEMA stg GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rw_dwh;
ALTER DEFAULT PRIVILEGES IN SCHEMA dds GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rw_dwh;
ALTER DEFAULT PRIVILEGES IN SCHEMA dm  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rw_dwh;
ALTER DEFAULT PRIVILEGES IN SCHEMA meta GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rw_dwh;
ALTER DEFAULT PRIVILEGES IN SCHEMA meta GRANT ALL ON SEQUENCES TO rw_dwh;
ALTER DEFAULT PRIVILEGES IN SCHEMA dm  GRANT EXECUTE ON FUNCTIONS TO rw_dwh;

ALTER DEFAULT PRIVILEGES IN SCHEMA dm  GRANT SELECT ON TABLES TO ro_marts;
ALTER DEFAULT PRIVILEGES IN SCHEMA rep GRANT SELECT ON TABLES TO ro_marts;
ALTER DEFAULT PRIVILEGES IN SCHEMA rep GRANT EXECUTE ON FUNCTIONS TO ro_marts;
