--CREATE SCHEMA ext;

DROP EXTERNAL TABLE IF EXISTS ext.customer_ext;
CREATE EXTERNAL TABLE ext.customer_ext (
    C_CUSTKEY INT,
    C_NAME VARCHAR(25),
    C_ADDRESS VARCHAR(40),
    C_NATIONKEY INTEGER,
    C_PHONE CHAR(15),
    C_ACCTBAL DECIMAL(15, 2),
    C_MKTSEGMENT CHAR(10),
    C_COMMENT VARCHAR(117)
)
LOCATION ('gpfdist://localhost:8081/customer.tbl_')
FORMAT 'TEXT' (DELIMITER '|');

DROP EXTERNAL TABLE IF EXISTS ext.orders_ext;
CREATE EXTERNAL TABLE  ext.orders_ext (
    O_ORDERKEY BIGINT,
    O_CUSTKEY INT,
    O_ORDERSTATUS CHAR(1),
    O_TOTALPRICE DECIMAL(15, 2),
    O_ORDERDATE DATE,
    O_ORDERPRIORITY CHAR(15),
    O_CLERK CHAR(15),
    O_SHIPPRIORITY INTEGER,
    O_COMMENT VARCHAR(79)
)
LOCATION ('gpfdist://localhost:8081/orders.tbl_')
FORMAT 'TEXT' (DELIMITER '|');

DROP EXTERNAL TABLE IF EXISTS ext.lineitem_ext;
CREATE EXTERNAL TABLE  ext.lineitem_ext (
    L_ORDERKEY BIGINT,
    L_PARTKEY INT,
    L_SUPPKEY INT,
    L_LINENUMBER INTEGER,
    L_QUANTITY DECIMAL(15, 2),
    L_EXTENDEDPRICE DECIMAL(15, 2),
    L_DISCOUNT DECIMAL(15, 2),
    L_TAX DECIMAL(15, 2),
    L_RETURNFLAG CHAR(1),
    L_LINESTATUS CHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE CHAR(10),
    L_COMMENT VARCHAR(44)
)
LOCATION ('gpfdist://localhost:8081/lineitem.tbl_')
FORMAT 'TEXT' (DELIMITER '|');

DROP EXTERNAL TABLE IF EXISTS ext.part_ext;
CREATE EXTERNAL TABLE  ext.part_ext (
    P_PARTKEY INT,
    P_NAME VARCHAR(55),
    P_MFGR CHAR(25),
    P_BRAND CHAR(10),
    P_TYPE VARCHAR(25),
    P_SIZE INTEGER,
    P_CONTAINER CHAR(10),
    P_RETAILPRICE DECIMAL(15, 2),
    P_COMMENT VARCHAR(23)
)
LOCATION ('gpfdist://localhost:8081/part.tbl_')
FORMAT 'TEXT' (DELIMITER '|');

DROP EXTERNAL TABLE IF EXISTS ext.supplier_ext;
CREATE EXTERNAL TABLE  ext.supplier_ext (
    S_SUPPKEY INT,
    S_NAME CHAR(25),
    S_ADDRESS VARCHAR(40),
    S_NATIONKEY INTEGER,
    S_PHONE CHAR(15),
    S_ACCTBAL DECIMAL(15, 2),
    S_COMMENT VARCHAR(101)
)
LOCATION ('gpfdist://localhost:8081/supplier.tbl_')
FORMAT 'TEXT' (DELIMITER '|');

DROP EXTERNAL TABLE IF EXISTS ext.partsupp_ext;
CREATE EXTERNAL TABLE  ext.partsupp_ext (
    PS_PARTKEY INT,
    PS_SUPPKEY INT,
    PS_AVAILQTY INTEGER,
    PS_SUPPLYCOST DECIMAL(15, 2),
    PS_COMMENT VARCHAR(199)
)
LOCATION ('gpfdist://localhost:8081/partsupp.tbl_')
FORMAT 'TEXT' (DELIMITER '|');

DROP EXTERNAL TABLE IF EXISTS ext.nation_ext;
CREATE EXTERNAL TABLE  ext.nation_ext (
    N_NATIONKEY INTEGER,
    N_NAME CHAR(25),
    N_REGIONKEY INTEGER,
    N_COMMENT VARCHAR(152)
)
LOCATION ('gpfdist://localhost:8081/nation.tbl_')
FORMAT 'TEXT' (DELIMITER '|');

DROP EXTERNAL TABLE IF EXISTS ext.region_ext;
CREATE EXTERNAL TABLE  ext.region_ext (
    R_REGIONKEY INTEGER,
    R_NAME CHAR(25),
    R_COMMENT VARCHAR(152)
)
LOCATION ('gpfdist://localhost:8081/region.tbl_')
FORMAT 'TEXT' (DELIMITER '|');


INSERT INTO tds2.customer
SELECT * FROM ext.customer_ext;

INSERT INTO tds2.orders
SELECT * FROM ext.orders_ext;

INSERT INTO tds2.lineitem
SELECT * FROM ext.lineitem_ext;

INSERT INTO tds2.part
SELECT * FROM ext.part_ext;

INSERT INTO tds2.partsupp
SELECT * FROM ext.partsupp_ext;

INSERT INTO tds2.supplier
SELECT * FROM ext.supplier_ext;

INSERT INTO tds2.nation
SELECT * FROM ext.nation_ext;

INSERT INTO tds2.region
SELECT * FROM ext.region_ext;


SELECT * FROM tds2.customer

