
GRANT USAGE ON SCHEMA public TO pxf_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO pxf_reader;


GRANT USAGE ON SCHEMA public TO etl_src;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO etl_src;


ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO pxf_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO etl_src;
